version: '3'

services:
  order_processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./config/:/config
      - /var/log/kse/:/var/log/kse/