version: '3'

services:
  stock_aggregator:
    container_name: stock_aggregator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./config/:/config
      - /var/log/kse/:/var/log/kse/