version: '3'

services:
  user_analytics:
    container_name: user_analytics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./config/:/config
      - /var/log/kse/:/var/log/kse/