version: '3'

services:
  stock_ingestor:
    container_name: stock_ingestor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./config/:/config
      - /var/log/kse/:/var/log/kse/